interface systemData {
    bookImg:string
    title:string
}
export class InitData{
   
    systemList:systemData[]=[
        {
        title:'1人大代表联系选民制度',
        bookImg:'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fpic1.zhimg.com%2F50%2Fv2-9e33105c633fdcdf5bf0beabdf4d9f1e_720w.jpg%3Fsource%3D54b3c3a5&refer=http%3A%2F%2Fpic1.zhimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=auto?sec=1663398012&t=65beecb7fdd4cbcd9d511604f7462281'
        },
        {
        title:'2人大代表联系选民制度',
        bookImg:'人大代表联系选民制度'
        },
        {
            title:'3人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
        },
        {
            title:'4人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
        },
        {
            title:'5人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
        },
        {
                title:'6人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
        },
        {
            title:'7人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
        },
        {
                title:'8人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
        },
        {
            title:'9人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
            },
            {
            title:'10人大代表联系选民制度',
            bookImg:'人大代表联系选民制度'
            },
            {
                title:'11人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
            },
            {
                title:'12人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
            },
            {
                title:'13人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
            },
            {
                    title:'15人大代表联系选民制度',
                    bookImg:'人大代表联系选民制度'
            },
            {
                title:'16人大代表联系选民制度',
                bookImg:'人大代表联系选民制度'
            },
    ]
 
    
}